### ISSUE TITLE
Excel parser: Integer error in .xlsx files 

### ISSUE THREAD

**Issue by JoeWolanski** [DeskGen/dgparse#32]
When parsing in-valued-column.xlsx I get the following traceback:
```
INFO:manifest.cli.main:Running fulfilment
Traceback (most recent call last):
  File "/opt/venvs/deskgen/bin/manifest", line 11, in <module>
    load_entry_point('manifest', 'console_scripts', 'manifest')()
  File "/opt/venvs/deskgen/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venvs/deskgen/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/opt/venvs/deskgen/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venvs/deskgen/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/opt/deploy/manifest/manifest/cli/main.py", line 20, in main
    getattr(fulfilment, name).run(manifestpath)
  File "/opt/deploy/manifest/manifest/fulfilment/inventory.py", line 34, in run
    workload = adapter.workload(config)
  File "/opt/deploy/manifest/manifest/adapters/localfile/xls_cell_line.py", line 34, in workload
    raw_json.extend(parse_xls(db_file))
  File "/opt/venvs/deskgen/local/lib/python2.7/site-packages/dgparse/excel.py", line 49, in parse
    headers = wsheet[1]  # always the attributes
  File "/opt/venvs/deskgen/local/lib/python2.7/site-packages/openpyxl/worksheet/worksheet.py", line 333, in __getitem__
    if ":" in key:
TypeError: argument of type 'int' is not iterable
```

It is trying to iterate on an int value type.

version of dgparse: `dgparse (0.0.1)`
version openpyxl: `openpyxl (2.3.0)` 

Requirements.txt needs:
- `pip install -e .`

enevolv-production server is using older version of openpyxl.

**Comment by JoeWolanski** [comment]
Enevolv dgparse has not been updated since Dec 2015 in commit 
`2699f600aafe1d400b113f264a3ba7c885761679`

my latest commit is 
`02f932c1d73d68a4044341fadab6b6b095bf3038`

This is why the openpyxl is outdated. 

I will update the version control of the openpyxl in setup.py to specify versioning to >=2.4.0

After upgrading the version of openpyxl 1204 of the 1228 strains have been uploaded successfully. 

Investigating the 24 missing strains separately.

**Comment by rodoyle** [comment]
@JoeWolanski This is purely due to the version of the xlsx reading library being out of date on selected servers.

Test suite is green locally.
